### ISSUE TITLE
edit input with $EDITOR

### ISSUE THREAD

**Issue by smondet** [diml/lambda-term#1]
Hi

This is a feature-request for a new action in `lambda-term-actions`: edit-with-editor

In *bash*, `C-x C-e` opens $EDITOR with the current command line in a temporary file and when closing the editor, it "sends" the file as input to the shell.

It would be great to have that for things like `utop`.

Cheers

**Comment by gasche** [comment]
This feature was requested again (by Sébastien but also MercurialAlchemist, independently) on [this reddit thread](https://www.reddit.com/r/ocaml/comments/3qjs1q/utop_is_a_much_better_toplevel_than_ocaml_if_you/).

**Comment by diml** [comment]
OK, I added this as well as `UTop.set_external_editor` in utop.

**Comment by gasche** [comment]
This seems slightly buggy on my machine. Here is what I do:

- start typing `let x =` in utop
- run C-x C-e
- complete in my editor the sentence into `let x = 1 + 1;;`
- close the editor
- utop now has the sentence `let x=let x = 1 + 1;;` on the input line

**Comment by diml** [comment]
Indeed, it's fixed
