### ISSUE TITLE
highlight default color

### ISSUE THREAD

**Issue by hannesm** [diml/lambda-term#19]
I would like to support both dark and light terminals, but still highlight the background of a specific item... at the moment I have to hardcode either `white` or `lblack` as background color -- since I cannot seem to find out whether `LTerm_style.default` is `black` or `white`... it would be great to have a `LTerm_style.default_highlight : color` function.

**Comment by diml** [comment]
Unfortunately I don't know how to query the background/foreground color from the terminal, I don't even know if it is possible. One way to highlight something in an independent way is to use the reverse attribute, which swap the background and foreground colors.

**Comment by hannesm** [comment]
thanks. now using reverse.
