### ISSUE TITLE
install fails with opam on cygwin platform

### ISSUE THREAD

**Issue by pela9** [diml/lambda-term#27]
Can not install lambda-term via opam on the cygwin platform.

```
genovese[~]$ opam install lambda-term
The following actions will be performed:
  ∗  install lambda-term 1.9

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lambda-term] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Processing  1/1: [lambda-term: ocamlfind remove]
#=== ERROR while installing lambda-term.1.9 ===================================#
# opam-version 1.2.2
# os           cygwin
# command      install -m 0755 /home/pela/.opam/4.02.3/build/lambda-term.1.9/_build/tools/lambda_term_actions.native /home/pela/.opam/4.02.3/bin/lambda-term-actions
# path         /home/pela/.opam/4.02.3/build/lambda-term.1.9
# exit-code    1
# env-file     /home/pela/.opam/log/log-17852-05296d.env
# stdout-file  /home/pela/.opam/log/log-17852-05296d.out
# stderr-file  /home/pela/.opam/log/log-17852-05296d.err
### stderr ###
# install: cannot create regular file '/home/pela/.opam/4.02.3/bin/lambda-term-actions': File exists



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install lambda-term 1.9
No changes have been performed
```

**Comment by diml** [comment]
Is the error in the log wrong or does the file `/home/pela/.opam/4.02.3/bin/lambda-term-actions` already exist?

**Comment by pela9** [comment]
Thanks for your attention.
I tried several times and made sure that the file (../lambda-term-actions) did not exist prior to the installation. So, either is the log message wrong or will the install script try to copy the file more than one time to the installation directory.

**Comment by diml** [comment]
lambda-term uses [oasis](https://github.com/ocaml/oasis) which handles the installation so this looks like an oasis related problem. We can try to debug this problem here, but since it probably affects all oasis packages, it would be best if you could report this to the oasis project directly

**Comment by pela9** [comment]
I fetched the sources for lambda-term with opam -b switch and then issued the make/make install commands manually, which seemed to work ok. So actually it could be a ocamlfind/opam issue.
