### ISSUE TITLE
Widgets not able to get focus

### ISSUE THREAD

**Issue by andrewray** [diml/lambda-term#28]
Specific case is a custom widget (with can_focus) which can scroll left and right.  Below it (in a vbox) I put a hbox with two buttons.

```
[left] [....expanding 'glue'....] [right]
```

Looking at the focussing logic in `lTerm_toplevel_impl.ml` it seems it only scans downwards from the centre point of the currently focussed widget which hits (and skips) the `glue`[1] but not the buttons,

It might be better to scan the rectangular area below the widget instead (perhaps with heuristics to look below right and left as well?).

Another alternative might be some way to forward focus from a `glue` widget.

[1] by `glue` I mean a `new t "glue"` widget used to control layout.

**Comment by diml** [comment]
TBH I haven't looked at this code in a while, but if you have an idea how to fix it, I'd be happy to merge a patch

**Comment by andrewray** [comment]
#29 attempts to address the issue.  It allows optional specification of target widgets when moving focus.

Widgets with `can_focus=true` can directly specify a target widget.

Widgets with `can_focus=false` can take part in the search for a target widget (if such a widget it 'hit' it can set a target widget).

Note that when a target widget is used it's not quite clear what to set `coord` to.  Currently I set it to the middle of the target widget.

Also, I have updated the `_oasis` file with a new test but not committed related oasis generated files as they don't appear in keeping with the ones in your repo.  Not sure what I've done wrong here.

**Comment by diml** [comment]
Thanks, for oasis, you should normally be able to build without generating the files first. If you just run `make` it will use oasis in _dynamic mode_. I generally do this as I find it distasteful to commit lots of generated files in the development repository

**Comment by andrewray** [comment]
Closing, thanks.  

RE oasis, I think ran `oasis setup` rather than `make distclean` to pick up changes at some point and polluted things.  I'll tidy it up by hand.
