### ISSUE TITLE
Adding features to a few widgets; label, frame, button

### ISSUE THREAD

**Issue by andrewray** [diml/lambda-term#34]
I'd like to make the following modification to some widgets, if you agree;

* label - allow left, right or centre justification
* frame - place optional text on the frame border
* button - make the brackets optional/configurable

I dunno if you prefer default constructor args or methods to do this (though I think for the button change, default args is easiest).

**Comment by andrewray** [comment]
Another small change I would like to introduce is an `auto_connect` field in LTerm_draw.point with a `?(auto:true)` arg to `draw_piece` so I can turn off the automatic connection logic.

**Comment by diml** [comment]
That all seems fine to me, default args seems best indeed
