### ISSUE TITLE
Jbuilder dependency

### ISSUE THREAD

**Issue by Reperator** [diml/lambda-term#49]
When opam updated from lambda-term 1.10.1 to 1.11 (I have lambda-term pinned to --dev-repo) it failed due to me not having Jbuilder installed. I think adding Jbuilder as a dependency to the `lambda-term.opam` file (and to the `README`) should fix this, but I couldn't get this to work on my machine. Manually installing Jbuilder worked though. I don't know anything about Jbuilder so I figured I'd just raise the issue.

**Comment by Reperator** [comment]
Also the `README` still mentions oasis.

**Comment by rgrinberg** [comment]
Yeah, and the dependencies mentioned in the readme don't mention the dependencies in the OPAM file. Maybe that section should just be deleted?

**Comment by diml** [comment]
Indeed, I updated the opam file and README
