### ISSUE TITLE
Lwt 3.0 compatible release

### ISSUE THREAD

**Issue by rgrinberg** [diml/lambda-term#50]
Would it be possible to release current master? 3.0 compat. is very convenient.

**Comment by diml** [comment]
Indeed, I'll try to do this today

**Comment by diml** [comment]
I submitted a new release of zed, once it's merged I'll submit one of lambda-term: https://github.com/ocaml/opam-repository/pull/9037

**Comment by diml** [comment]
The new release is in opam
