### ISSUE TITLE
Mutable strings build problem

### ISSUE THREAD

**Issue by kugg** [diml/lambda-term#58]
Im using Ocaml 4.05.0 and I am getting build errors due to mutable strings, probably because of safe-string being applied somewhere. I bumped in to this error while trying to install utop.
I reproduced the error on commit 636ed411102c6bda2684d82c308f72187684efd0 (current HEAD in master).

<pre>
lambda-term$ make
jbuilder build --dev @install @examples/all
      ocamlc src/.lambda_term.objs/lTerm_widget_callbacks.{cmi,cmti} (exit 2)
(cd _build/default && /home/user/.opam/4.05.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -safe-string -g -bin-annot -I /home/user/.opam/4.05.0/lib/bytes -I /home/user/.opam/4.05.0/lib/camomile -I /home/user/.opam/4.05.0/lib/lwt -I /home/user/.opam/4.05.0/lib/lwt_react -I /home/user/.opam/4.05.0/lib/ocaml/threads -I /home/user/.opam/4.05.0/lib/react -I /home/user/.opam/4.05.0/lib/result -I /home/user/.opam/4.05.0/lib/zed -no-alias-deps -I src/.lambda_term.objs -o src/.lambda_term.objs/lTerm_widget_callbacks.cmi -c -intf src/lTerm_widget_callbacks.mli)
File "src/lTerm_widget_callbacks.mli", line 13, characters 35-49:
Warning 3: deprecated: module Lwt_sequence
 This module is an implementation detail of Lwt. See
   https://github.com/ocsigen/lwt/issues/361
File "src/lTerm_widget_callbacks.mli", line 19, characters 34-48:
Warning 3: deprecated: module Lwt_sequence
 This module is an implementation detail of Lwt. See
   https://github.com/ocsigen/lwt/issues/361
File "src/lTerm_widget_callbacks.mli", line 22, characters 32-46:
Warning 3: deprecated: module Lwt_sequence
 This module is an implementation detail of Lwt. See
   https://github.com/ocsigen/lwt/issues/361
File "src/lTerm_widget_callbacks.mli", line 1:
Error: Some fatal warnings were triggered (3 occurrences)
      ocamlc src/.lambda_term.objs/lTerm_windows.{cmo,cmt} (exit 2)
(cd _build/default && /home/user/.opam/4.05.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -safe-string -g -bin-annot -I /home/user/.opam/4.05.0/lib/bytes -I /home/user/.opam/4.05.0/lib/camomile -I /home/user/.opam/4.05.0/lib/lwt -I /home/user/.opam/4.05.0/lib/lwt_react -I /home/user/.opam/4.05.0/lib/ocaml/threads -I /home/user/.opam/4.05.0/lib/react -I /home/user/.opam/4.05.0/lib/result -I /home/user/.opam/4.05.0/lib/zed -no-alias-deps -I src/.lambda_term.objs -o src/.lambda_term.objs/lTerm_windows.cmo -c -impl src/lTerm_windows.ml)
File "src/lTerm_windows.ml", line 66, characters 2-22:
Warning 3: deprecated: Lwt_unix.execute_job
 Use Lwt_unix.run_job.
File "src/lTerm_windows.ml", line 1:
Error: Some fatal warnings were triggered (1 occurrences)
    ocamlopt src/.lambda_term.objs/lTerm_windows.{cmx,o} (exit 2)
(cd _build/default && /home/user/.opam/4.05.0/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -safe-string -g -I /home/user/.opam/4.05.0/lib/bytes -I /home/user/.opam/4.05.0/lib/camomile -I /home/user/.opam/4.05.0/lib/lwt -I /home/user/.opam/4.05.0/lib/lwt_react -I /home/user/.opam/4.05.0/lib/ocaml/threads -I /home/user/.opam/4.05.0/lib/react -I /home/user/.opam/4.05.0/lib/result -I /home/user/.opam/4.05.0/lib/zed -no-alias-deps -I src/.lambda_term.objs -o src/.lambda_term.objs/lTerm_windows.cmx -c -impl src/lTerm_windows.ml)
File "src/lTerm_windows.ml", line 66, characters 2-22:
Warning 3: deprecated: Lwt_unix.execute_job
 Use Lwt_unix.run_job.
File "src/lTerm_windows.ml", line 1:
Error: Some fatal warnings were triggered (1 occurrences)
      ocamlc src/.lambda_term.objs/lTerm_unix.{cmo,cmt} (exit 2)
(cd _build/default && /home/user/.opam/4.05.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -safe-string -g -bin-annot -I /home/user/.opam/4.05.0/lib/bytes -I /home/user/.opam/4.05.0/lib/camomile -I /home/user/.opam/4.05.0/lib/lwt -I /home/user/.opam/4.05.0/lib/lwt_react -I /home/user/.opam/4.05.0/lib/ocaml/threads -I /home/user/.opam/4.05.0/lib/react -I /home/user/.opam/4.05.0/lib/result -I /home/user/.opam/4.05.0/lib/zed -no-alias-deps -I src/.lambda_term.objs -o src/.lambda_term.objs/lTerm_unix.cmo -c -impl src/lTerm_unix.ml)
File "src/lTerm_unix.ml", line 342, characters 32-51:
Error: This expression has type bytes but an expression was expected of type
         string
    ocamlopt src/.lambda_term.objs/lTerm_unix.{cmx,o} (exit 2)
(cd _build/default && /home/user/.opam/4.05.0/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -safe-string -g -I /home/user/.opam/4.05.0/lib/bytes -I /home/user/.opam/4.05.0/lib/camomile -I /home/user/.opam/4.05.0/lib/lwt -I /home/user/.opam/4.05.0/lib/lwt_react -I /home/user/.opam/4.05.0/lib/ocaml/threads -I /home/user/.opam/4.05.0/lib/react -I /home/user/.opam/4.05.0/lib/result -I /home/user/.opam/4.05.0/lib/zed -no-alias-deps -I src/.lambda_term.objs -o src/.lambda_term.objs/lTerm_unix.cmx -c -impl src/lTerm_unix.ml)
File "src/lTerm_unix.ml", line 342, characters 32-51:
Error: This expression has type bytes but an expression was expected of type
         string
      ocamlc src/.lambda_term.objs/lTerm.{cmo,cmt} (exit 2)
(cd _build/default && /home/user/.opam/4.05.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -safe-string -g -bin-annot -I /home/user/.opam/4.05.0/lib/bytes -I /home/user/.opam/4.05.0/lib/camomile -I /home/user/.opam/4.05.0/lib/lwt -I /home/user/.opam/4.05.0/lib/lwt_react -I /home/user/.opam/4.05.0/lib/ocaml/threads -I /home/user/.opam/4.05.0/lib/react -I /home/user/.opam/4.05.0/lib/result -I /home/user/.opam/4.05.0/lib/zed -no-alias-deps -I src/.lambda_term.objs -o src/.lambda_term.objs/lTerm.cmo -c -impl src/lTerm.ml)
File "src/lTerm.ml", line 115, characters 16-34:
Warning 3: deprecated: module Lwt_sequence
 This module is an implementation detail of Lwt. See
   https://github.com/ocsigen/lwt/issues/361
File "src/lTerm.ml", line 120, characters 18-36:
Warning 3: deprecated: module Lwt_sequence
 This module is an implementation detail of Lwt. See
   https://github.com/ocsigen/lwt/issues/361
File "src/lTerm.ml", line 334, characters 32-51:
Error: This expression has type bytes but an expression was expected of type
         string
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 1
</pre>

**Comment by kugg** [comment]
Problem seen in version 1.12 but not in version 1.11 using jbuilder 1.0+beta17.

**Comment by yomimono** [comment]
`lambda-term` version 1.12 needs a version of `camomile` later than 0.8.5; 0.8.6 and 0.8.7 both seem to work.  There is a PR to opam-repository reflecting his at https://github.com/ocaml/opam-repository/pull/11556.

**Comment by rgrinberg** [comment]
Thanks for updating the constraints Mindy.
